In [1]:
import numpy as np
import pandas as pd

from dfmp import DataFrameMP

In [2]:
def fit(par0=None, par1=None):
    return par0 + par1

class DataFrameFits(DataFrameMP):
    
    def fit(self, idx):
        return fit(**df.loc[idx].to_dict())

In [3]:
df = pd.DataFrame(np.random.randn(10, 2), index=['i'+str(ii) for ii in range(10)], columns=['par0', 'par1'])
dfmp = DataFrameFits(df, folder='./data')
display(dfmp.apply_method(dfmp.fit).df)
display(dfmp.df['par0'] + dfmp.df['par1'])

           0
i0  0.591527
i1  0.065002
i2 -1.189441
i3  1.177366
i4 -0.939181
i5  0.535604
i6  1.053641
i7  0.182737
i8  1.061266
i9 -2.092263

i0    0.591527
i1    0.065002
i2   -1.189441
i3    1.177366
i4   -0.939181
i5    0.535604
i6    1.053641
i7    0.182737
i8    1.061266
i9   -2.092263
dtype: float64

In [19]:
import numpy as np
import pandas as pd
import time

def fun1(par0=None, par1=None):
    return par0 + par1

df = pd.DataFrame(np.random.randn(10, 2), index=['i'+str(ii) for ii in range(10)], columns=['par0', 'par1'])
dfmp = DataFrameMP(df, folder='./data')
dfmp_res = dfmp.apply(fun1, processes=8, columns=['res'])
display((dfmp.df['par0'] + dfmp.df['par1']).head())
display(dfmp_res.df.head())
print('should conserve metadata', dfmp_res.folder)
print('concat columns')
dfmp_join = dfmp.join(dfmp_res)
display(dfmp_join.df)
print('should conserve metadata', dfmp_join.folder)
# print(dfmp.apply(fun2, processes=8, columns=['res', 'string']).df.head())
# print(dfmp.apply(fun3, kwargs=dict(arg_extra=100), processes=8, columns=['res', 'string']).df.head())
# print(dfmp.apply(fun2, processes=8, columns=['res']).df.head())

i0    0.270045
i1    0.485954
i2   -2.832043
i3    0.223194
i4    0.620002
dtype: float64

         res
i0  0.270045
i1  0.485954
i2 -2.832043
i3  0.223194
i4  0.620002

should conserve metadata ./data
concat columns

        par0      par1       res
i0  0.113466  0.156579  0.270045
i1  0.046758  0.439196  0.485954
i2 -0.796277 -2.035765 -2.832043
i3  0.123777  0.099417  0.223194
i4  1.624538 -1.004536  0.620002
i5 -0.309558 -0.750696 -1.060254
i6  0.035248  0.013123  0.048371
i7  0.775475  1.467296  2.242771
i8 -0.925690 -0.138075 -1.063765
i9 -0.852383 -1.258819 -2.111202

should conserve metadata ./data

In [11]:
import numpy as np
import pandas as pd
import time

def fun1(par0=None, par1=None):
    return par0 + par1

def fun2(par0=None, par1=None, folder=None):
    return [par0 + par1, folder + '2']

def fun3(par0=None, par1=None, folder=None, arg_extra=None):
    return [par0 + par1 + arg_extra, folder + '3']

df = pd.DataFrame(np.random.randn(10, 3), index=['i'+str(ii) for ii in range(10)], columns=['par0', 'par1', 'par2'])
dfmp = DataFrameMP(df, folder='./data')
print(dfmp.apply(fun1, processes=8, columns=['res']).df.head())
print(dfmp.apply(fun2, processes=8, columns=['res', 'string']).df.head())
print(dfmp.apply(fun3, kwargs=dict(arg_extra=100), processes=8, columns=['res', 'string']).df.head())
# print(dfmp.apply(fun2, processes=8, columns=['res']).df.head())

         res
i0 -0.766743
i1 -0.167190
i2 -2.837968
i3  0.308716
i4  0.186387
         res   string
i0 -0.766743  ./data2
i1 -0.167190  ./data2
i2 -2.837968  ./data2
i3  0.308716  ./data2
i4  0.186387  ./data2
           res   string
i0   99.233257  ./data3
i1   99.832810  ./data3
i2   97.162032  ./data3
i3  100.308716  ./data3
i4  100.186387  ./data3